version: '3'
services:
  web:
    build: .
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}
      ZENHUB_TOKEN: ${ZENHUB_TOKEN}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_BACKEND: ${DB_BACKEND}
      DB_PORT: 5432
    ports:
    - "8000:8000"
